name: sulam_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 6.0.3
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  flutter_secure_storage: ^8.1.0
  firebase_storage: 13.0.3
  firebase_app_check: 0.4.1+1
  image_picker: ^1.1.0
  file_picker: ^8.0.0
  url_launcher: ^6.3.2

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Add intl package for date formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/CodeQuest.png
